sudo: required

dist: bionic

language: go

go:
#  - master
# - 1.13.x
  - 1.12.x

go_import_path: github.com/enkeys/qdr-operator
services:
  - docker

git:
  depth: 1

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - KUBERNETES_VERSION=$(curl -k -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    #- OPERATORSDK_VERSION="$(curl -s https://api.github.com/repos/operator-framework/operator-sdk/releases/latest | grep tag_name | sed -E "s/.*\"([^\"]+)\".*/\1/")"
    - OPERATORSDK_VERSION=v0.10.0
    - GO111MODULE=on

before_install:
# Install Go Dep
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure

# Get tools
- go get sigs.k8s.io/kind
- go get github.com/wadey/gocovmerge
- go get golang.org/x/lint/golint
- go get github.com/mattn/goveralls

# Setup kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo mv kubectl /usr/local/bin/

# Setup minikube.
#- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#- chmod +x minikube
#- sudo mv minikube /usr/local/bin/

# Run minikube
#- mkdir -p $HOME/.kube $HOME/.minikube
#- touch $KUBECONFIG
#- sudo minikube start --vm-driver=none --kubernetes-version=${KUBERNETES_VERSION}
#- sudo minikube update-context
#- sudo chown -R travis $HOME/.minikube/

# Create a new Kubernetes cluster using KinD
- kind create cluster
- export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
- kubectl cluster-info

# Install Operator SDK
- curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATORSDK_VERSION}/operator-sdk-${OPERATORSDK_VERSION}-x86_64-linux-gnu
- chmod +x operator-sdk
- sudo mv operator-sdk /usr/local/bin/

# Setup
- cd $GOPATH/src/github.com/enkeys/qdr-operator
- dep ensure && dep status

# before_script:

script:
- cd $GOPATH/src/github.com/enkeys/qdr-operator
- make
- go test -v -race "./test/e2e" #-covermode=count -coverprofile=organize.cov

# after_success:
#- gocovmerge *.cov */*.cov > merged.cov erprofile
#- $GOPATH/bin/goveralls -coverprofile merged.coverprofile -service=travis-ci
